server:
  port: 8082

spring:
  application:
    name: microservice-consumer-movie-ribbon
  #thymeleaf模板配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

user:
   userServiceUrl: http://microservice-provider-user/getUser/