server:
  port: 8761

eureka:
  client:
    #是否将自己注册到Eureka Sever
    register-with-eureka: false
    #是否从Eureka Sever上获取注册信息
    fetch-registry: false
    service-url:
          defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: microservice-discovery-eureka